# Generated by Django 3.2.7 on 2021-09-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourHood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('occupants_count', models.IntegerField(blank=True, null=True)),
                ('hood_pic', models.ImageField(default='default.png', upload_to='hoods/profiles/')),
                ('police_call', models.IntegerField(blank=True, null=True)),
                ('hospital_call', models.IntegerField(blank=True, null=True)),
                ('Fire_call', models.IntegerField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='hood.profile')),
            ],
        ),
    ]
