# Generated by Django 3.2.7 on 2021-09-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='brief',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
