# Generated by Django 3.2.7 on 2021-09-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_alter_business_brief'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='email',
            new_name='emails',
        ),
    ]
