# Generated by Django 3.2.7 on 2021-09-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_rename_email_business_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='owner',
        ),
    ]
