# Generated by Django 3.2.7 on 2021-09-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_rename_user_business_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('insecurity', 'insecurity'), ('death', 'death'), ('advertisement', 'advertisement'), ('fundraising', 'fundraising'), ('general information', 'general information'), ('wedding/pre-wedding', 'wedding/pre-wedding'), ('hood personnel', 'hood personnel')], max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.neighbourhood')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hood.profile')),
            ],
        ),
    ]
